[package]
name = "escrow-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-contract = { path = "../patches/casper-contract" }
casper-types = "6.1"
wee_alloc = "0.4"

[[bin]]
name = "escrow-contract"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = true