[package]
name = "escrow-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-contract = "5.1"
casper-types = "6.1"

[[bin]]
name = "escrow-contract"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = true